version: 2
models:
  - name: WyvernExchangeV2_call_transferOwnership
    columns:
      - name: newOwner
      - name: call_success
      - name: call_block_number
      - name: call_block_time
      - name: call_trace_address
      - name: call_tx_hash
      - name: contract_address
      - name: dt
