apiVersion: batch/v1
kind: CronJob
metadata:
  name: dbt-ethereum-source
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: dbt-ethereum-source
              image: { { your_docker_image } }
              env:
                - name: SPARK_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: dbt-spark-sts
                      key: database
                - name: SPARK_HOST
                  valueFrom:
                    secretKeyRef:
                      name: dbt-spark-sts
                      key: host
                - name: SPARK_PORT
                  valueFrom:
                    secretKeyRef:
                      name: dbt-spark-sts
                      key: port
              imagePullPolicy: Always
          restartPolicy: OnFailure
