
config-version: 2

name: 'ethereum_source'
version: '0.1.0'
require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  ethereum_source:
    +materialized: view
    +schema: stg_ethereum

vars:
  ethereum_source:
    transactions: "{{ source('ethereum', 'transactions') }}"
    token_transfers: "{{ source('ethereum', 'token_transfers') }}"    
    tokens: "{{ source('ethereum', 'tokens') }}"
    contracts: "{{ source('ethereum', 'contracts') }}"
    blocks: "{{ source('ethereum', 'blocks') }}"
    logs: "{{ source('ethereum', 'logs') }}"
    traces: "{{ source('ethereum', 'tokens') }}"
    receipts: "{{ source('ethereum', 'receipts') }}"

    #Variables to enable or disable models if you do not have the respective table.
    using_traces: true
    using_logs: true
    using_token_transfers: true
    using_receipts: false
