config-version: 2
name: ethereum_source
profile: ethereum_source
version: 0.1.16
require-dbt-version:
  - '>=1.0.0'
  - <2.0.0
models:
    ethereum_source:
        stg:
            +materialized: view
            +schema: stg
            +tags:
              - chain_ethereum
              - level_standardize
              - proj_global
        codegen:
            metamask:
                +schema: metamask
                +tags:
                  - chain_ethereum
                  - level_parse
                  - proj_metamask
            curve:
                +schema: curve
                +tags:
                  - chain_ethereum
                  - level_parse
                  - proj_curve
            rariable:
                +schema: rariable
                +tags:
                  - chain_ethereum
                  - level_parse
                  - proj_rariable
            looksrare:
                +schema: looksrare
                +tags:
                  - chain_ethereum
                  - level_parse
                  - proj_looksrare
            common:
                +schema: common
                +tags:
                  - chain_ethereum
                  - level_parse
                  - proj_common
            superrare:
                +schema: superrare
                +tags:
                  - chain_ethereum
                  - level_parse
                  - proj_superrare
            foundation:
                +schema: foundation
                +tags:
                  - chain_ethereum
                  - level_parse
                  - proj_foundation
            yearn:
                +schema: yearn
                +tags:
                  - chain_ethereum
                  - level_parse
                  - proj_yearn
            ens:
                +schema: ens
                +tags:
                  - chain_ethereum
                  - level_parse
                  - proj_ens
            opensea:
                +schema: opensea
                +tags:
                  - chain_ethereum
                  - level_parse
                  - proj_opensea
            cryptopunks:
                +schema: cryptopunks
                +tags:
                  - chain_ethereum
                  - level_parse
                  - proj_cryptopunks
        erc20:
            +materialized: view
            +schema: erc20
            +tags:
              - chain_ethereum
              - level_modeling
              - proj_erc20
        erc721:
            +materialized: view
            +schema: erc721
            +tags:
              - chain_ethereum
              - level_modeling
              - proj_erc721
        erc1155:
            +materialized: view
            +schema: erc1155
            +tags:
              - chain_ethereum
              - level_modeling
              - proj_erc1155
vars:
    ethereum_schema: ethereum
    ethereum_database: labelstry
    ethereum_source:
        transactions: "{{ source('labelstry', 'transactions') }}"
        token_transfers: "{{ source('labelstry', 'token_transfers') }}"
        tokens: "{{ source('labelstry', 'tokens') }}"
        contracts: "{{ source('labelstry', 'contracts') }}"
        blocks: "{{ source('labelstry', 'blocks') }}"
        logs: "{{ source('labelstry', 'logs') }}"
        traces: "{{ source('labelstry', 'traces') }}"
        using_traces: true
        using_logs: true
        using_token_transfers: true
        dt: not-set
