ethereum_source:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      schema: "{{ env_var('SPARK_DATABASE') }}"
      host: "{{ env_var('SPARK_HOST') }}"
      port: "{{ env_var('SPARK_PORT') | as_number }}"
      threads: 4
