name: Compile dbt and push to s3

on:
  push:
    tags:
      - "compile-*"
    branches:
      - "main"

env:
  SPARK_DATABASE: ${{ secrets.DBT_SPARK_DATABASE }}
  SPARK_HOST: ${{ secrets.DBT_SPARK_HOST }}
  SPARK_PORT: ${{ secrets.DBT_SPARK_PORT }}

jobs:
  compile-n-push-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install-deps
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt deps --profiles-dir ."

      - name: compile-dbt
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt compile --profiles-dir ."

      - name: Upload manifest to s3
        uses: zdurham/s3-upload-github-action@master
        env:
          FILE: ./target/manifest.json
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          S3_KEY: ${{ secrets.AWS_S3_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
